name: CI/CD Backend HIS to AWS EC2

on:
  push:
    branches: [ deploy ]

jobs:
  # 1. Job: Checkout và Build Docker image
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-his:latest

  # 2. Job: Push image lên Docker Hub
  push_image:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-his:latest

  # 3. Job: Deploy lên EC2
  deploy_ec2:
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/nestjs-his:latest

            echo "Stop old containers"
            docker ps -q --filter "publish=3000" | xargs -r docker stop
            docker ps -aq --filter "publish=3000" | xargs -r docker rm

            echo "Remove old container if exists"
            docker rm -f nestjs-his || true

            echo "Run new container"
            docker run -d -p 3000:3000 \
              --name nestjs-his \
              --env DB_HOST=${{ secrets.DB_HOST }} \
              --env DB_PORT=3306 \
              --env DB_USERNAME=${{ secrets.DB_USERNAME }} \
              --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --env DB_DATABASE=${{ secrets.DB_DATABASE }} \
              --env JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              --env JWT_EXPIRATION_TIME=1h \
              --env SOURCE_URL=http://${{ secrets.EC2_HOST }}:3000 \
              --env ORIGIN_URL=${{ secrets.FONTEND_URL }} \
              --env AVAILABLE_METHODS=GET,HEAD,PUT,PATCH,POST,DELETE \
              --network=bridge \
              --restart=no \
              ${{ secrets.DOCKER_USERNAME }}/nestjs-his:latest

            echo "Clean unused images"
            docker image prune -a -f
